version: "3.8"
services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    stdin_open: true
#    volumes:
#      - ./frontend:/usr/src/app
#      - /usr/src/app/node_modules
    restart: always
    networks:
      - node-network
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
#    volumes:
#      - ./backend:/usr/src/app
#      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - node-network
    ports:
      - "8080:8080"

  mongo:
    restart: always
    image: mongo:7.0.8
    networks:
      - node-network
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db


networks:
  node-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
