version: "3.8"
services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    stdin_open: true
#    volumes:
#      - ./frontend:/usr/src/app
#      - /usr/src/app/node_modules
    restart: always
    networks:
      - node-network
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
#    volumes:
#      - ./backend:/usr/src/app
#      - /usr/src/app/node_modules
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: ${PORT}
    depends_on:
      - mongo
    networks:
      - node-network
    ports:
      - "8080:8080"

  mongo:
    restart: always
    image: mongo:4.2.0
    networks:
      - node-network
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

#  nginx:
#    build:
#      context: nginx
#    container_name: nginx
#    restart: always
#    tty: true
#    ports:
#      - "8000:80"
#    networks:
#      - node-network
#    depends_on:
#      - backend
#      - frontend

networks:
  node-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
