name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      PORT: ${{ secrets.PORT }}
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: Install Dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install
    - name: Run Tests
      run: |
        cd frontend && npm test
        cd ../backend && npm test
    - name: Create .env file
      run: |
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" > backend/.env
        echo "PORT=${{ secrets.PORT }}" >> backend/.env
        echo "API_KEY=${{ secrets.API_KEY }}" >> backend/.env
    - name: Build Docker Images
      run: |
          docker-compose build
          docker-compose up -d
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Images to Docker Hub
      run: |
        docker-compose push



