name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: Install Dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        PORT: ${{ secrets.PORT }}
    - name: Run Tests
      run: |
        cd frontend && npm test
        cd ../backend && npm test
    - name: Build Docker Images
      run: docker-compose build
    - name: Run Integration Tests
      run: docker-compose up -d

